tasks:
  - name: 本地启动
    init: ./gradlew install
    command: ./gradlew package
ports:
  - name: server
    port: 8080
    description: 至流云开放访问端口
    visibility: public
  - name: agent
    port: 30177
    description: 代理开放访问端口
    visibility: public
  - name: flink-ui
    port: 8081
    description: flink ui
    visibility: public

# 安装必要插件
vscode:
  extensions:
    - akamud.vscode-theme-onedark
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - eamodio.gitlens
    - redhat.java
    - GabrielBB.vscode-lombok
    - PKief.material-icon-theme
    - vscjava.vscode-java-dependency
    - vscjava.vscode-spring-boot-dashboard
    - vmware.vscode-spring-boot
