name: website deploy

on:
  workflow_dispatch:
    inputs:
      admin_github_token:
        description: '管理员github token'
        required: true
        type: string

env:
  ADMIN_GITHUB_TOKEN: ${{ inputs.admin_github_token }}

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        node:
          - '18'

    steps:

      - name: Set timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date

      - name: Checkout flink-yun
        uses: actions/checkout@v4
        with:
          token: ${{ env.ADMIN_GITHUB_TOKEN }}
          repository: "isxcode/flink-yun"
          ref: 'main'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.0.6
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build with Nodejs
        run: |
          cd docs
          pnpm install --force
          pnpm run generate

      - name: Tar dist
        run: |
          tar -czf dist.tar.gz /home/runner/work/flink-yun/flink-yun/docs/dist
      
      - name: Upload website to Ali oss
        uses: tvrcgo/oss-action@master
        with:
          key-id: ${{ secrets.ALI_OSS_KEY_ID }}
          key-secret: ${{ secrets.ALI_OSS_KEY_SECRET }}
          region: oss-cn-shanghai
          bucket: isxcode
          timeout: 1200
          assets: |
            /home/runner/work/flink-yun/flink-yun/dist.tar.gz:/zhiliuyun/

      - name: deploy website
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          timeout: 1800s
          script: |
            curl -ssL https://isxcode.oss-cn-shanghai.aliyuncs.com/zhiliuyun/dist.tar.gz -o /tmp/dist.tar.gz
            tar -vzxf /tmp/dist.tar.gz -C /data/nginx/html
            rm -rf /data/nginx/ssl/zhiliuyun.isxcode.com.pem
            rm -rf /data/nginx/ssl/zhiliuyun.isxcode.com.key
            cp /root/zhiliuyun.isxcode.com.pem /data/nginx/ssl/zhiliuyun.isxcode.com.pem
            cp /root/zhiliuyun.isxcode.com.key /data/nginx/ssl/zhiliuyun.isxcode.com.key
            nginx -s reload