name: deploy zhiliuyun

on:
  workflow_dispatch:
    inputs:
      admin_github_token:
        description: '管理员github token'
        required: true
        type: string
      deploy_date:
        description: '发布日期,例如2023-12-12'
        required: true
        type: string

env:
  ADMIN_GITHUB_TOKEN: ${{ inputs.admin_github_token }}

jobs:

  download:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

      - name: Set timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date

      - name: Checkout flink-yun
        uses: actions/checkout@v4
        with:
          token: ${{ env.ADMIN_GITHUB_TOKEN }}
          repository: "isxcode/flink-yun"
          ref: 'main'

      - name: deploy demo
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          timeout: 1800s
          script: |
            rm -rf /tmp/zhiliuyun.tar.gz
            curl -ssL https://isxcode.oss-cn-shanghai.aliyuncs.com/zhiliuyun/zhiliuyun.tar.gz -o /tmp/zhiliuyun.tar.gz

  ssl:
    needs: download
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

      - name: config ssl
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            rm -rf /data/nginx/ssl/zhiliuyun-demo.isxcode.com.pem
            rm -rf /data/nginx/ssl/zhiliuyun-demo.isxcode.com.key
            cp /root/zhiliuyun-demo.isxcode.com.pem /data/nginx/ssl/zhiliuyun-demo.isxcode.com.pem
            cp /root/zhiliuyun-demo.isxcode.com.key /data/nginx/ssl/zhiliuyun-demo.isxcode.com.key
            nginx -s reload

  deploy:
    needs: ssl
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

      - name: Set timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date

      - name: deploy demo
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          timeout: 1800s
          script: |
            tar -vzxf /tmp/zhiliuyun.tar.gz -C /opt/
            bash /opt/zhiliuyun/bin/stop.sh
            rm -rf /opt/zhiliuyun/conf/application-local.yml
            cp /root/application-local.yml /opt/zhiliuyun/conf/application-local.yml
            rm -rf /opt/zhiliuyun/resources_bak/resources_${{ inputs.deploy_date }}_bak
            cp -r /opt/zhiliuyun/resources /opt/zhiliuyun/resources_bak/resources_${{ inputs.deploy_date }}_bak
            bash /opt/zhiliuyun/bin/start.sh --print-log=false
            sleep 120
            until curl -s https://zhiliuyun-demo.isxcode.com/tools/open/health | grep "UP"; do
              echo "Waiting for service to be available..."
              sleep 1
            done